name: CI & CD

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: kevin77200/${{ github.event.repository.name }}:${{ github.sha }}

  deploy-to-cluster:
    name: deploy to cluster
    runs-on: ubuntu-latest
    needs: docker
    steps:
    -
      name: check if deployment exists
      run: |
        if kubectl get deployment gh-action-test -n test; then
          echo "Deployment exists."
          echo "deployment_exists=true" >> $GITHUB_ENV
        else
          echo "Deployment does not exist."
          echo "deployment_exists=false" >> $GITHUB_ENV
        fi
    -
      name: update image if deployment exists
      if: env.deployment_exists == 'true'
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: -n test set image --record deployment/gh-action-test gh-action-test=kevin77200/gh-action-test:${{ github.sha }}
    -
      name: create deployment if not exists
      if: env.deployment_exists == 'false'
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: -n test create deployment gh-action-test --image=kevin77200/gh-action-test:${{ github.sha }} --image-pull-secrets='dockerhub-secret'
    -
      name: verify deployment
      uses: steebchen/kubectl@v2.0.0
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.28"
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: -n test rollout status deployment/gh-action-test
