name: CI

on:
  push:

jobs:
  # docker_build_push_without_tests:
  #   runs-on: ubuntu-latest
  #   env:
  #     PUSH_IMAGE: false
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v6
  #       with:
  #         # Testing purposes
  #         push: ${{ env.PUSH_IMAGE }}
  #         tags: kevin77200/${{ github.event.repository.name }}:${{ github.sha }}
  
  docker_build_push_with_tests:
    runs-on: ubuntu-latest
    env:
      PUSH_IMAGE: true
      IMAGE_TAG: "kevin77200/${{ github.event.repository.name }}:${{ github.sha }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG}}

      - name: Run Docker container for testing
        run: docker run -d -p 8080:80 ${{ env.IMAGE_TAG}}

      - name: Test Nginx Response
        run: |
          curl --retry 5 --retry-connrefused --retry-delay 2 http://localhost:8080 -o response.html && \ 
          grep -q "<h1>This is the test number:<b>42</b></h1>" response.html

      - name: Clean Docker container
        run: docker rm -f ${{ env.IMAGE_TAG}}

      - name: Remove the Docker images
        run: docker rmi ${{ env.IMAGE_TAG}}

      - name: Push image
        if: ${{ success() && env.PUSH_IMAGE }}
        run: docker push ${{ env.IMAGE_TAG}}